name: Demo Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: windows-2022
    steps:
     # - uses: actions/checkout@v3
     # - run: dotnet test

      - name: Checkout  
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.401

        # restore dependencies  
      - name: Install dependencies
        run: dotnet restore
  
      # set pr number, if it's a pr build
      - name: set pr build number
        id: PRNUMBER
        if: ${{ github.event_name == 'pull_request' }}
        uses: kkak10/pr-number-action@v1.3
  
        # set report file and title 
      - name: Set Test Title
        run: | 
              if (${{ github.event_name == 'pull_request' }})
              then
                echo "title=Test Run for PR #${{steps.PRNUMBER.outputs.pr}} (${{github.run_number}})" >> $GITHUB_ENV
                echo "file_name=TestReport.${{steps.PRNUMBER.outputs.pr}}.${{github.run_number}}.md" >> $GITHUB_ENV              
              else
                echo "title=Test Run ${{github.run_number}}" >> $GITHUB_ENV
                echo "file_name=TestReport.${{github.run_number}}.md" >> $GITHUB_ENV
              fi


