name: Demo Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: windows-2022
    steps:
     # - uses: actions/checkout@v3
     # - run: dotnet test

      - name: Checkout  
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.100

        # restore dependencies  
      - name: Install dependencies
        run: dotnet restore
  
      # set pr number, if it's a pr build
      - name: set pr build number
        id: PRNUMBER
        if: ${{ github.event_name == 'pull_request' }}
        uses: kkak10/pr-number-action@v1.3
  
        # set report file and title 
      - name: Set Test Title
        run: |               
                echo "title=Test Run for PR " >> $GITHUB_ENV
                echo "file_name=TestReport.md" >> $GITHUB_ENV              
        # run tests with built project
      - name: Test PR      
        run: dotnet test $config --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.file_name}};Title=${{env.title}};"
        


